version: '2.1'

## EXECUTORS
executors:
  java:
    docker:
      - image: openjdk:7
    working_directory: ~/repo

## COMMANDS
commands:

  checkout-alpine:
    description: Install requirements for checkout
    steps:
      - run:
          name: "Install requirements for checkout"
          command: |
            apt-get update && apt-get install --no-install-recommends -y git curl wget
      - checkout

  javaversion:
    steps:
      - checkout-alpine
      - attach_workspace:
          at: .
      - run:
          name: javaversion
          command: java -version


## JOBS
  showjavaversion:
    executor: java
    steps:
      - javaversion

## WORKFLOWS
workflows:
  Code quality PHP 7.4:
    jobs:
      - showjavaversion
