version: '2.1'

## EXECUTORS
executors:
  java:
    docker:
      - image: maven:3.5.3-jdk-8-alpine
    working_directory: ~/repo

## COMMANDS
commands:

  checkout-alpine:
    description: Install requirements for checkout
    steps:
      #- run:
      #    name: "Install requirements for checkout"
      #    command: |
      #      apt-get update && apt-get install --no-install-recommends -y git curl wget
      - checkout

  javaversion:
    steps:
      - checkout-alpine
      - attach_workspace:
          at: .
      - run:
          name: javaversion
          #command: java -version && export DISPLAY=:0.0 && echo "stating Junit" && junit
          command: mvn package && mvn test


## JOBS
jobs:
  showjavaversion:
    executor: java
    steps:
      - javaversion

## WORKFLOWS
workflows:
  Code quality Java:
    jobs:
      - showjavaversion
